### ISSUE TITLE
Realizar Commit

### ISSUE THREAD

**Issue by Reyezonia** [Reyezonia/Navegantes#2]
Cada integrante del equipo debe realizar por lo menos un commit inicial en el repositorio

**Comment by yeimipao1** [comment]
Hola equipo

**Comment by JsebasD** [comment]
Primer commit Juan Sebastian Duque Gil

**Comment by jhonfa328** [comment]
primer commit john duque

**Comment by IsaacFerrucho** [comment]
Primer commit Isaac Ferucho
